#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SPU.Mobile.Droid.Resource", IsApplication=true)]

namespace SPU.Mobile.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int arrobalogin = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int avatar = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int averiamain = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int averiaround = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int ayuda = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int back = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int casos = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int centroidt = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int chat = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int comment = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int comparadormain = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int comparadorround = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int conciliacion = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int consultacaso = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int contactos = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int dau = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int deberes1 = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int deberes10 = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int deberes11 = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int deberes2 = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int deberes3 = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int deberes4 = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int deberes5 = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int deberes6 = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int deberes7 = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int deberes8 = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int deberes9 = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int depositodocu = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int derechos1 = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int derechos10 = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int derechos11 = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int derechos12 = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int derechos13 = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int derechos14 = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int derechos2 = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int derechos3 = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int derechos4 = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int derechos5 = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int derechos6 = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int derechos7 = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int derechos8 = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int derechos9 = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int editarperfil = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int facebookicon = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int faqs = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int fbcontact = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int gob2 = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int google = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int googleicon = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int gracias = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int home = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int htindotel = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int huella = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int idt = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int image1 = 2130837558;
			
			// aapt resource value: 0x7F020037
			public const int image2 = 2130837559;
			
			// aapt resource value: 0x7F020038
			public const int image3 = 2130837560;
			
			// aapt resource value: 0x7F020039
			public const int info = 2130837561;
			
			// aapt resource value: 0x7F02003A
			public const int instcontact = 2130837562;
			
			// aapt resource value: 0x7F02003B
			public const int jpgicon = 2130837563;
			
			// aapt resource value: 0x7F02003C
			public const int llamada = 2130837564;
			
			// aapt resource value: 0x7F02003D
			public const int location = 2130837565;
			
			// aapt resource value: 0x7F02003E
			public const int location2 = 2130837566;
			
			// aapt resource value: 0x7F02003F
			public const int @lock = 2130837567;
			
			// aapt resource value: 0x7F020040
			public const int locklogin = 2130837568;
			
			// aapt resource value: 0x7F020041
			public const int loght = 2130837569;
			
			// aapt resource value: 0x7F020042
			public const int loght2 = 2130837570;
			
			// aapt resource value: 0x7F020043
			public const int logohashtag = 2130837571;
			
			// aapt resource value: 0x7F020044
			public const int logout = 2130837572;
			
			// aapt resource value: 0x7F020045
			public const int logowhite = 2130837573;
			
			// aapt resource value: 0x7F020046
			public const int logowhite2 = 2130837574;
			
			// aapt resource value: 0x7F020047
			public const int masreclama = 2130837575;
			
			// aapt resource value: 0x7F020048
			public const int menu = 2130837576;
			
			// aapt resource value: 0x7F020049
			public const int microsoft = 2130837577;
			
			// aapt resource value: 0x7F02004A
			public const int misderechos = 2130837578;
			
			// aapt resource value: 0x7F02004B
			public const int notificacion = 2130837579;
			
			// aapt resource value: 0x7F02004C
			public const int nuevareclama = 2130837580;
			
			// aapt resource value: 0x7F02004D
			public const int pdficon = 2130837581;
			
			// aapt resource value: 0x7F02004E
			public const int planbg = 2130837582;
			
			// aapt resource value: 0x7F02004F
			public const int pngicon = 2130837583;
			
			// aapt resource value: 0x7F020050
			public const int proxconciliacion = 2130837584;
			
			// aapt resource value: 0x7F020051
			public const int reclamaccom = 2130837585;
			
			// aapt resource value: 0x7F020052
			public const int reclamacioni = 2130837586;
			
			// aapt resource value: 0x7F020053
			public const int satisfecho = 2130837587;
			
			// aapt resource value: 0x7F020054
			public const int search = 2130837588;
			
			// aapt resource value: 0x7F020055
			public const int share = 2130837589;
			
			// aapt resource value: 0x7F020056
			public const int simulador2 = 2130837590;
			
			// aapt resource value: 0x7F020057
			public const int simuladorround = 2130837591;
			
			// aapt resource value: 0x7F020058
			public const int splash3_android = 2130837592;
			
			// aapt resource value: 0x7F020059
			public const int splashind = 2130837593;
			
			// aapt resource value: 0x7F02005A
			public const int splash_screen = 2130837594;
			
			// aapt resource value: 0x7F02005B
			public const int tpcasos = 2130837595;
			
			// aapt resource value: 0x7F02005C
			public const int tpcontactos = 2130837596;
			
			// aapt resource value: 0x7F02005D
			public const int tphome = 2130837597;
			
			// aapt resource value: 0x7F02005E
			public const int tpmas = 2130837598;
			
			// aapt resource value: 0x7F02005F
			public const int tpnuevareclama = 2130837599;
			
			// aapt resource value: 0x7F020060
			public const int twcontact = 2130837600;
			
			// aapt resource value: 0x7F020061
			public const int twitterIcon = 2130837601;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int icon_round = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int launcher_foreground = 2131034115;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int facebook_app_id = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppCompatDialogStyle = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int MainTheme = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int MainTheme_Base = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int Theme_Splash = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F080000
			public const int file_paths = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int network_security_config = 2131230721;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
